// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updaterevokerefresh.sql

package database

import (
	"context"
)

const revokeRefresh = `-- name: RevokeRefresh :exec
UPDATE refresh_tokens
SET
    revoked_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE token = $1
`

func (q *Queries) RevokeRefresh(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefresh, token)
	return err
}
